### ISSUE TITLE
Representing concordance between samples from the same patient

### ISSUE THREAD

**Issue by mcewenrk** [vanallenlab/comut#3]
Hello,

this is really cool package; I really like the flexibility and ease with which the plots may be generated. I like the ability to show more than one mutation as a box with a slash but was wondering whether you'd considered using this view to represent the mutation status of two samples from the same patient? That is, the upper triangle of the box could represent an early timepoint sample while the lower triangle might represent a later sample from the same patient - coloured according to the mutation detected, for example.
I guess this may be possible in the current codebase by adapting how the input is formatted. I appreciate you also already have the functionality for representing the "same patient" but think this would be a valuable addition to an already excellent package.
Thanks for making the package available !

**Comment by jett-crowdis** [comment]
Thanks for your suggestion! I think your idea is an excellent one. It is possible using the current codebase - all you would need to do is define a different "class" of mutations for each timepoint, so rather than Missense, it would be pre_Missense and post_Missense. You would then give these values the same color mapping and use the `value_order` parameter of `add_categorical_data` to set it such that values with `pre` would come before those with `post` (eg `value_order = ['pre_Missense', 'post_Missense']`). This would make it so that all early timepoints appear as upper left triangles and late timepoints as lower right triangles. One would then need to do some reconfiguring of the legend to rename and combine the two "values" into one. 

Given that this idea can be achieved with the current structure without *too* much work, I'm going to avoid implementing this idea unless more people find it useful. Thank you very much for the suggestion though - always looking for ways to improve!
